name: Upstream updates

on:
  schedule:
    # probably go with nightly here, 1am west coast for now
    - cron: 0 9 * * *
  workflow_dispatch:

jobs:
  pull_in_upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git remote add incommon https://github.internet2.edu/docker/shib-sp.git
          git fetch incommon
          git checkout -b master incommon/master
          git push -u origin master
          git checkout -b 3.4.0_02092023_rocky8_multiarch incommon/3.4.0_02092023_rocky8_multiarch
          git push -u origin 3.4.0_02092023_rocky8_multiarch:3.4.0_multiarch
          echo "local branches updated"
